/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eolChecker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
//        Application classUnderTest = new Application();
//        assertTrue(classUnderTest., "someLibraryMethod should return 'true'");
    }
}
